### ISSUE TITLE
Caching of logged in pages?

### ISSUE THREAD

**Issue by martinszy** [mysociety/yournextrepresentative#455]
I got one user report that said the page was in english and it said "logged in as mark". This is very odd.

**Comment by martinszy** [comment]
I did another user test, and she also got this error, which went away when I deleted nginx cache, so the problem is there.
Logged in pages should send a cache-expires header with the current time.

**Comment by dracos** [comment]
If necessary, I guess that could be done, but it shouldn't be necessary. The site correctly sends a Vary header saying the cache varies on Accept-Language and Cookie, so if the nginx cache obeyed that it would not show something cached with one Cookie header to someone with another Cookie header. It looks like this was a bug in nginx only fixed in 1.7.7 and you're using 1.6.2. The easiest solution if you can't upgrade would be for you to add Accept-Encoding and Cookie to the proxy_cache_key configuration variable so nginx knows that it should key cache based on those two.

**Comment by martinszy** [comment]
Ok, I've added the follwing directive

    proxy_cache_key "$host$request_uri $cookie_user";

To the location section for ynr, to avoid unnecesary caching in other
parts of the app and to increase the change that ynr is properly
cached.

I didn't find the full list of variables to use in this directive, so
I just copied from here:

http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_key


2015-07-22 4:53 GMT-03:00 M Somerville <notifications@github.com>:

> If necessary, I guess that could be done, but it shouldn't be necessary.
> The site correctly sends a Vary header saying the cache varies on
> Accept-Language and Cookie, so if the nginx cache obeyed that it would not
> show something cached with one Cookie header to someone with another Cookie
> header. It looks like this was a bug in nginx only fixed in 1.7.7 and
> you're using 1.6.2. The easiest solution if you can't upgrade would be for
> you to add Accept-Encoding and Cookie to the proxy_cache_key configuration
> variable so nginx knows that it should key cache based on those two.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mysociety/yournextrepresentative/issues/455#issuecomment-123600282>
> .
>



-- 
*Martín Szyszlican*
Desarrollo web usable y accesible
martinszyszlican.com

**Comment by martinszy** [comment]
I still get the same behavior :(

2015-07-22 14:14 GMT-03:00 Martín Szyszlican <martinsz@gmail.com>:

> Ok, I've added the follwing directive
>
>     proxy_cache_key "$host$request_uri $cookie_user";
>
> To the location section for ynr, to avoid unnecesary caching in other parts of the app and to increase the change that ynr is properly cached.
>
> I didn't find the full list of variables to use in this directive, so I just copied from here:
>
> http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_key
>
>
> 2015-07-22 4:53 GMT-03:00 M Somerville <notifications@github.com>:
>
>> If necessary, I guess that could be done, but it shouldn't be necessary.
>> The site correctly sends a Vary header saying the cache varies on
>> Accept-Language and Cookie, so if the nginx cache obeyed that it would not
>> show something cached with one Cookie header to someone with another Cookie
>> header. It looks like this was a bug in nginx only fixed in 1.7.7 and
>> you're using 1.6.2. The easiest solution if you can't upgrade would be for
>> you to add Accept-Encoding and Cookie to the proxy_cache_key configuration
>> variable so nginx knows that it should key cache based on those two.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mysociety/yournextrepresentative/issues/455#issuecomment-123600282>
>> .
>>
>
>
>
> --
> *Martín Szyszlican*
> Desarrollo web usable y accesible
> martinszyszlican.com
>
>
>
>


-- 
*Martín Szyszlican*
Desarrollo web usable y accesible
martinszyszlican.com

**Comment by dracos** [comment]
"I still get the same behavior :(" – you have added to proxy_cache_key a variable that contains the contents of the "user" cookie. This project does not set a cookie called "user", it sets a cookie called "sessionid". So you should use `$cookie_sessionid` (<a href="http://nginx.org/en/docs/http/ngx_http_core_module.html#var_cookie_">documentation on `$cookie_`</a> ). You should also, for completeness, add `$http_accept_language` as well, to match the Vary header (<a href="http://nginx.org/en/docs/http/ngx_http_core_module.html#var_http_">documentation on `$http_`</a>). So try:

    proxy_cache_key "$host$request_uri$cookie_sessionid$http_accept_language";
and hopefully that will work.

**Comment by martinszy** [comment]
I did a quick test and it seemed to work.
Needs more verification.
Thanks.

2015-07-23 3:46 GMT-03:00 M Somerville <notifications@github.com>:

> "I still get the same behavior :(" – you have added to proxy_cache_key a
> variable that contains the contents of the "user" cookie. This project does
> not set a cookie called "user", it sets a cookie called "sessionid". So you
> should use $cookie_sessionid (documentation on $cookie_
> <http://nginx.org/en/docs/http/ngx_http_core_module.html#var_cookie_> ).
> You should also, for completeness, add $http_accept_language as well, to
> match the Vary header (documentation on $http_
> <http://nginx.org/en/docs/http/ngx_http_core_module.html#var_http_>). So
> try:
>
> proxy_cache_key "$host$request_uri$cookie_sessionid$http_accept_language";
>
> and hopefully that will work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mysociety/yournextrepresentative/issues/455#issuecomment-123997509>
> .
>



-- 
*Martín Szyszlican*
Desarrollo web usable y accesible
martinszyszlican.com

**Comment by dracos** [comment]
I'm afraid this does not appear to be fixed, I am e.g. logging in and still seeing pages as if I am logged out If you have set up the key as I suggest, I'm not sure why it is still not working, but if you can't work out why it is not caching correctly, I can only suggest that you turn off the nginx proxy cache, as the site is basically unusable with this problem. You could perhaps install varnish and use that instead, as I know that handles HTTP headers correctly.

**Comment by martinszy** [comment]
I've disabled the nxing cache for now and I will rely on cloudflare.
